services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    platform: linux/arm64/v8
    networks:
      - delivery

  web:
    image: songkg7/web
    container_name: web
    platform: linux/amd64
    ports:
      - 8080:8080
    networks:
      - delivery

networks:
  delivery:
    driver: bridge
