### Sign Up
POST http://localhost:8080/customer/sign-up
Content-Type: application/json

{
  "name": "John Doe",
  "phoneNumber": "123-456-7890",
  "addresses": [
    {
      "city": "New York",
      "street": "NY",
      "zipcode": "10001"
    },
    {
      "city": "Texas",
      "street": "TX",
      "zipcode": "12345"
    }
  ]
}

### Remove Address

### Create Restaurant
POST http://localhost:8080/restaurant
Content-Type: application/json

{
  "name": "Restaurant 1",
  "address": "123 Main Street",
  "phoneNumber": "123-456-7890",
  "businessHours": "9:00 AM - 9:00 PM",
  "menus": [
    {
      "name": "Menu 1",
      "price": 1000
    },
    {
      "name": "Menu 2",
      "price": 2000
    }
  ]
}

### Single Menu Order
POST http://localhost:8080/order
Content-Type: application/json

{
  "customerId": 1,
  "restaurantId": 1,
  "menus": [
    {
      "menuId": 1,
      "quantity": 1
    }
  ]
}

### Multi Menu Order
POST http://localhost:8080/order
Content-Type: application/json

{
  "customerId": 1,
  "restaurantId": 1,
  "menus": [
    {
      "menuId": 1,
      "quantity": 1
    },
    {
      "menuId": 2,
      "quantity": 2
    }
  ]
}

### Create Review
POST http://localhost:8080/review
Content-Type: application/json

{
  "customerId": 1,
  "restaurantId": 1,
  "orderId": 1,
  "rating": 5,
  "content": "This is a content"
}
